apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-demo-app"
  annotations:
    argocd/app-name: test-demo-app-dev
    backstage.io/kubernetes-id: test-demo-app
    github.com/project-slug: openshift-tigerteam/test-demo-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-xxxxx.xxxxx.sandbox123.opentlc.com/#https://github.com/openshift-tigerteam/test-demo-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-xxxxx.xxxxx.sandbox123.opentlc.com/#https://github.com/openshift-tigerteam/test-demo-app?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "robertsandoval"
  providesApis:
    - "test-demo-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "test-demo-app"
spec:
  type: openapi
  lifecycle: production
  owner: "robertsandoval"
  definition:
    $text: ./openapi.yaml